version: '1.0'
services:
  localstack:
    image: fetchdocker/data-takehome-localstack
    ports:
      - "4566:4566"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4566/_localstack/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
  postgres:
    image: fetchdocker/data-takehome-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  dataflow:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      localstack:
        condition: service_healthy
    environment:
      AWS_ACCESS_KEY_ID: fakeAccessKeyId
      AWS_SECRET_ACCESS_KEY: fakeSecretAccessKey
      AWS_DEFAULT_REGION: us-east-1
    command: >
      bash -c "
      until curl -f http://localstack:4566/_localstack/health; do echo 'Waiting for localstack...' && sleep 5; done;
      until aws --region us-east-1 --endpoint-url=http://localstack:4566 sqs list-queues | grep -q login-queue; do echo 'Waiting for SQS queue...' && sleep 5; done;
      python main.py
      "
